-- Referrals: per-user invite codes + redemption tracking + idempotent code generator.
-- Companion to feat/referrals (refer-a-friend feature).

-- 1. Per-user invite code on the users table (lazy-generated by generate_invite_code RPC).
alter table public.users
  add column if not exists invite_code text unique;

create index if not exists users_invite_code_idx
  on public.users (invite_code)
  where invite_code is not null;

-- 2. Redemption ledger.
create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  inviter_id uuid references public.users(id) on delete set null,
  invitee_id uuid not null references public.users(id) on delete cascade,
  invite_code text not null,
  source text not null check (source in ('clipboard', 'manual', 'universal_link')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (invitee_id),
  check (inviter_id is null or inviter_id <> invitee_id)
);

create index if not exists referrals_inviter_idx
  on public.referrals (inviter_id)
  where inviter_id is not null;

-- 3. RLS: clients can read their own role-relevant rows; inserts go through the
-- redeem-referral edge function with service-role privileges (no client-side INSERT policy).
alter table public.referrals enable row level security;

drop policy if exists "invitee can read own referral" on public.referrals;
create policy "invitee can read own referral"
  on public.referrals for select
  to authenticated
  using (invitee_id = auth.uid());

drop policy if exists "inviter can read own referrals" on public.referrals;
create policy "inviter can read own referrals"
  on public.referrals for select
  to authenticated
  using (inviter_id = auth.uid());

-- 4. Idempotent invite-code generator.
-- Returns the existing code if the user already has one, otherwise generates a 6-char
-- base32 code (A-Z and 2-9, excluding ambiguous 0/O/I/1) and retries on collision.
create or replace function public.generate_invite_code(target_user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  existing_code text;
  candidate text;
  attempt int;
begin
  -- Caller must be the user themselves (defense in depth even though edge fns use service role).
  if auth.uid() is not null and auth.uid() <> target_user_id then
    raise exception 'Cannot generate invite code for another user';
  end if;

  -- Already has one?
  select invite_code into existing_code
    from public.users
    where id = target_user_id;

  if existing_code is not null then
    return existing_code;
  end if;

  -- Generate + retry on collision (max 5 attempts; collision probability negligible).
  for attempt in 1..5 loop
    candidate := '';
    for i in 1..6 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;

    update public.users
      set invite_code = candidate
      where id = target_user_id
        and invite_code is null;

    if found then
      return candidate;
    end if;

    -- Either collision (unique violation handled by partial conflict) or already set by another transaction:
    -- re-read.
    select invite_code into existing_code
      from public.users
      where id = target_user_id;

    if existing_code is not null then
      return existing_code;
    end if;
  end loop;

  raise exception 'Failed to generate unique invite code after 5 attempts';
end;
$$;

revoke all on function public.generate_invite_code(uuid) from public;
grant execute on function public.generate_invite_code(uuid) to authenticated;

-- 5. PostHog-side comment for future reference: events are emitted from the
-- redeem-referral edge function (invite_redeemed / invite_redeem_failed) and from
-- the React Native client (invite_share_sheet_opened, invite_code_generated, etc).
