name: Front End CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        working-directory: Unify-front-end
        run: npm install

      - name: Run tests
        # ignore test for now as it is not implemented yet
        working-directory: Unify-front-end
        run: echo "Skipping tests"


      - name: Build
        working-directory: Unify-front-end
        run: npm run build

      - name: Deploy
        working-directory: Unify-front-end
        run: npm run deploy
