name: Full Stack CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  front-end:
    name: Front End CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Pull Amplify Environment
        run: |
          amplify pull \
            --appId ${{ secrets.AMPLIFY_APP_ID }} \
            --envName ${{ secrets.AMPLIFY_ENV_NAME }} \
            --amplify "{\"envName\":\"${{ secrets.AMPLIFY_ENV_NAME }}\"}" \
            --frontend "{\"frontend\":\"javascript\",\"config\":{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm run build\",\"StartCommand\":\"npm start\"}}" \
            --providers "{\"awscloudformation\":{\"region\":\"${{ secrets.AWS_REGION }}\",\"accessKeyId\":\"${{ secrets.AWS_ACCESS_KEY_ID }}\",\"secretAccessKey\":\"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"}}" \
            --yes

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: unify-front-end/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        working-directory: unify-front-end
        run: npm install

      - name: Run TypeScript
        working-directory: unify-front-end
        run: npx tsc --noEmit

      - name: Build the project
        working-directory: unify-front-end
        run: npx expo export

      - name: Deploy
        working-directory: unify-front-end
        run: npm run deploy

  back-end:
    name: Back End CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: unify-back-end/node_modules
          key: ${{ runner.os }}-npm-backend-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        working-directory: unify-back-end
        run: npm install

      - name: Run TypeScript
        working-directory: unify-back-end
        run: npx tsc --noEmit     

      - name: Build the server
        working-directory: unify-back-end
        run: npm run build

      # - name: Start server for testing
      #   working-directory: unify-back-end
      #   run: node dist/index.js &